defaults: ../../grpo_math_1B.yaml

grpo:
  num_prompts_per_step: 2
  num_generations_per_prompt: 8
  max_num_steps: 600
  max_val_samples: 64
  val_batch_size: 64
  val_at_start: true
  val_at_end: true
  val_period: 100
  skip_reference_policy_logprobs_calculation: true
  adv_estimator:
    name: oapl

loss_fn:
  name: oapl
  reference_policy_kl_penalty: 0.0
  use_importance_sampling_correction: false
  vstar_beta: 1.0
  policy_beta: 1.0e-3
  length_normalize_log_ratio: false
  sync_interval: 100

checkpointing:
  enabled: true
  checkpoint_dir: results/oapl-gemma3-1b-it-dapomath17k-1n1g-dtensor1
  save_period: 100
  keep_top_k: null
  save_optimizer: false

policy:
  model_name: google/gemma-3-1b-it
  tokenizer:
    name: google/gemma-3-1b-it
  train_global_batch_size: 16
  train_micro_batch_size: 1
  generation_batch_size: 4
  logprob_batch_size: 1
  max_total_sequence_length: 3072
  logprob_chunk_size: 2048
  make_sequence_length_divisible_by: 1
  offload_optimizer_for_logprob: true
  optimizer:
    kwargs:
      lr: 1.0e-6
      weight_decay: 0.01
  scheduler:
    - name: torch.optim.lr_scheduler.LinearLR
      kwargs:
        start_factor: 0.1
        end_factor: 1.0
        total_iters: 10
    - name: torch.optim.lr_scheduler.ConstantLR
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones:
        - 10
  dtensor_cfg:
    enabled: true
    tensor_parallel_size: 1
    activation_checkpointing: true
  megatron_cfg:
    enabled: false
  sequence_packing:
    enabled: false
  dynamic_batching:
    enabled: true
    train_mb_tokens: 3072
    logprob_mb_tokens: 3072
  generation:
    max_new_tokens: 2048
    vllm_cfg:
      gpu_memory_utilization: 0.45
      max_model_len: 3072

data:
  max_input_seq_length: 1024
  train:
    dataset_name: DAPOMath17K
  validation:
    dataset_name: DAPOMathAIME2024
  default:
    prompt_file: examples/prompts/cot.txt
    system_prompt_file: null

env:
  math:
    num_workers: 8
    math_verify_impl: hf_math_verify

logger:
  log_dir: logs/oapl-gemma3-1b-it-dapomath17k-1n1g-dtensor1
  wandb:
    name: oapl-gemma3-1b-it-dapomath17k-1n1g-dtensor1
  mlflow:
    run_name: oapl-gemma3-1b-it-dapomath17k-1n1g-dtensor1

cluster:
  gpus_per_node: 1
  num_nodes: 1
